# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-11-01 17:08
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rbcapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Codigo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_utilizada', models.DateTimeField(null=True, verbose_name='Data utilizada')),
                ('codigo', models.CharField(max_length=100, unique=True)),
                ('id_usuario', models.ForeignKey(default=24, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
