# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-11-01 19:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rbcapp', '0002_codigo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='pergunta',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='resposta',
        ),
    ]
