# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-11-01 19:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbcapp', '0003_auto_20191101_1614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codigo',
            name='codigo',
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
